//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCTHD
    {
        public string MaHoaDon { get; set; }
        public string MaSanPham { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
